BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "country" (
	"cnt_id"	integer,
	"cnt_continent"	varchar(255) NOT NULL,
	"cnt_name"	varchar(255) NOT NULL,
	"cnt_region"	varchar(255) NOT NULL,
	PRIMARY KEY("cnt_id")
);
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Myanmar ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','India ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','China ','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Indonesia ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Pakistan ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Bangladesh ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Japan ','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Philippines ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Vietnam ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Iran ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Turkey ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Thailand ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','South Korea','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Iraq ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Afghanistan ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Yemen ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Uzbekistan ','Central Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Malaysia','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Saudi Arabia ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Nepal ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','North Korea','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Syria ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Sri Lanka ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Kazakhstan ','Central Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Cambodia ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Jordan ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','United Arab Emirates','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Tajikistan','Central Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Azerbaijan','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Israel','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Laos ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Turkmenistan ','Central Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Kyrgyzstan','Central Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Singapore ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Lebanon ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Palestine','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Oman ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Kuwait ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Georgia ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Mongolia ','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Qatar ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Armenia ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Bahrain ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Timore-Leste','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Cyprus ','Western Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Bhutan ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Maldives ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Brunei ','Southern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Taiwan ','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Hong Kong','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Asia','Macao ','Eastern Asia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Nigeria ','West Africa

');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Ethiopia ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Egypt ','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Democratic Republic of the Congo','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Tanzania ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','South Africa','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Kenya ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Sudan ','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Uganda','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Algeria ','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Angola ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Morocco ','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Mozambique ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Ghana','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Madagascar','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Côte d''Ivoire','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Cameroon ','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Niger ','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Mali ','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Burkina Faso','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Malawi ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Zambia ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Chad ','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Somalia ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Senegal ','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Zimbabwe ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Guinea ','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Benin ','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Rwanda ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Burundi ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Tunisia ','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','South Sudan','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Togo ','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Sierra Leone','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Libya ','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Congo','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Liberia','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Central African Republic','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Mauritania','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Eritrea','Northern africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Namibia ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Gambia ','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Gabon ','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Botswana ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Lesotho ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Guinea-Bissau','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Equatorial Guinea','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Mauritius ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Eswatini ','Southern Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Djibouti ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Comoros ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Cabo Verde','West Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Sao Tome & Principe','Central Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Africa','Seychelles ','East Africa');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','United States of America','Northern America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Canada','Northern America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Mexico','Northern America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Guatemala','Central America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Belize','Central America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Honduras','Central America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','El Salvador','Central America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Nicaragua','Central America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Costa Rica','Central America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Panama','Central America');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Cuba','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Haiti','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Dominican Republic','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Jamaica','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Trinidad and Tobago','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Bahamas','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Barbados','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Saint Lucia','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Grenada','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Saint Vincent and the Grenadines','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Antigua and Barbuda','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Dominica','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('North America','Saint Kitts and Nevis','Caribbean');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Brazil ','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Colombia','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Argentina','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Peru','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Venezuela','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Chile','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Ecuador','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Bolivia','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Paraguay','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Uruguay','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Guyana','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','Suriname','Southern America ');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('South America','United Kingdom','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Ireland','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Iceland','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Norway','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Sweden','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Finland','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Denmark','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Estonia','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Latvia','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Lithuania','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','France','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Germany','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Netherlands','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Belgium','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Luxembourg','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Switzerland','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Liechtenstein','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Monaco','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Andorra','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Vatican City','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Spain','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Portugal','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Italy','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Greece','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Croatia','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Bosnia and Herzegovina','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Albania','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Slovenia','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Montenegro','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','North Macedonia','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Malta','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','San Marino','Northern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Ukraine','Eastern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Poland','Central Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Romania','Eastern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Hungary','Central Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Czech Republic','Central Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Slovakia','Central Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Bulgaria','Southeast Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Belarus','Eastern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Serbia','Southern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Moldova','Eastern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Serbia','Southern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Montenegro','Southern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Bosnia and Herzegovina','Southern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Albania','Southern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Croatia','Central Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','North Macedonia','Southern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Kosovo','Southern Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Europe','Liechtenstein','Western Europe');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Australia ','Australia and New Zealand');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','New Zealand','Australia and New Zealand');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Papua New Guinea','Melanesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Fiji ','Melanesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Solomon Islands','Melanesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Vanuatu ','Melanesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Samoa ','Polynesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Kiribati ','Micronesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Micronesia ','Micronesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Tonga ','Polynesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Marshall Islands','Micronesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Palau ','Micronesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Nauru ','Micronesia');
INSERT INTO "country" (cnt_continent, cnt_name, cnt_region)  VALUES ('Australia','Tuvalu ','Micronesia');
COMMIT;
