INSERT INTO country (continent, name, region)
VALUES
('Africa','Algeria','Northern Africa'),
('Africa','Angola','Southern Africa'),
('Africa','Benin','West Africa'),
('Africa','Botswana','Southern Africa'),
('Africa','Burkina Faso','West Africa'),
('Africa','Burundi','East Africa'),
('Africa','Cabo Verde','West Africa'),
('Africa','Cameroon','Central Africa'),
('Africa','Central African Republic','Central Africa'),
('Africa','Chad','Central Africa'),
('Africa','Comoros','East Africa'),
('Africa','Congo','Central Africa'),
('Africa','Côte d''Ivoire','West Africa'),
('Africa','Democratic Republic of the Congo','Central Africa'),
('Africa','Djibouti','East Africa'),
('Africa','Egypt','Northern Africa'),
('Africa','Equatorial Guinea','Central Africa'),
('Africa','Eritrea','East Africa'),
('Africa','Eswatini','Southern Africa'),
('Africa','Ethiopia','East Africa'),
('Africa','Gabon','Central Africa'),
('Africa','Gambia','West Africa'),
('Africa','Ghana','West Africa'),
('Africa','Guinea','West Africa'),
('Africa','Guinea-Bissau','West Africa'),
('Africa','Kenya','East Africa'),
('Africa','Lesotho','Southern Africa'),
('Africa','Liberia','West Africa'),
('Africa','Libya','Northern Africa'),
('Africa','Madagascar','Southern Africa'),
('Africa','Malawi','Southern Africa'),
('Africa','Mali','West Africa'),
('Africa','Mauritania','West Africa'),
('Africa','Mauritius','East Africa'),
('Africa','Morocco','Northern Africa'),
('Africa','Mozambique','Southern Africa'),
('Africa','Namibia','Southern Africa'),
('Africa','Niger','West Africa'),
('Africa','Nigeria','West Africa'),
('Africa','Rwanda','East Africa'),
('Africa','Sao Tome & Principe','Central Africa'),
('Africa','Senegal','West Africa'),
('Africa','Seychelles','East Africa'),
('Africa','Sierra Leone','West Africa'),
('Africa','Somalia','East Africa'),
('Africa','South Africa','Southern Africa'),
('Africa','South Sudan','East Africa'),
('Africa','Sudan','Northern Africa'),
('Africa','Tanzania','East Africa'),
('Africa','Togo','West Africa'),
('Africa','Tunisia','Northern Africa'),
('Africa','Uganda','East Africa'),
('Africa','Zambia','Southern Africa'),
('Africa','Zimbabwe','Southern Africa'),
('Asia','Afghanistan','Southern Asia'),
('Asia','Armenia','Western Asia'),
('Asia','Azerbaijan','Western Asia'),
('Asia','Bahrain','Western Asia'),
('Asia','Bangladesh','Southern Asia'),
('Asia','Bhutan','Southern Asia'),
('Asia','Brunei','Southern Asia'),
('Asia','Cambodia','South-Eastern Asia'),
('Asia','China','Eastern Asia'),
('Asia','Cyprus','Western Asia'),
('Asia','Georgia','Western Asia'),
('Asia','Hong Kong','Eastern Asia'),
('Asia','India','Southern Asia'),
('Asia','Indonesia','Southern Asia'),
('Asia','Iran','Southern Asia'),
('Asia','Iraq','Western Asia'),
('Asia','Israel','Western Asia'),
('Asia','Japan','Eastern Asia'),
('Asia','Jordan','Western Asia'),
('Asia','Kazakhstan','Central Asia'),
('Asia','Kuwait','Western Asia'),
('Asia','Kyrgyzstan','Central Asia'),
('Asia','Laos','South-Eastern Asia'),
('Asia','Lebanon','Western Asia'),
('Asia','Macao','Eastern Asia'),
('Asia','Malaysia','South-Eastern Asia'),
('Asia','Maldives','Southern Asia'),
('Asia','Mongolia','Eastern Asia'),
('Asia','Myanmar','South-Eastern Asia'),
('Asia','Nepal','Southern Asia'),
('Asia','North Korea','Eastern Asia'),
('Asia','Oman','Western Asia'),
('Asia','Pakistan','Southern Asia'),
('Asia','Palestine','Western Asia'),
('Asia','Philippines','South-Eastern Asia'),
('Asia','Qatar','Western Asia'),
('Asia','Saudi Arabia','Western Asia'),
('Asia','Singapore','South-Eastern Asia'),
('Asia','South Korea','Eastern Asia'),
('Asia','Sri Lanka','Southern Asia'),
('Asia','Syria','Western Asia'),
('Asia','Taiwan','Eastern Asia'),
('Asia','Tajikistan','Central Asia'),
('Asia','Thailand','South-Eastern Asia'),
('Asia','Timore-Leste','South-Eastern Asia'),
('Asia','Turkey','Western Asia'),
('Asia','Turkmenistan','Central Asia'),
('Asia','United Arab Emirates','Western Asia'),
('Asia','Uzbekistan','Central Asia'),
('Asia','Vietnam','South-Eastern Asia'),
('Asia','Yemen','Western Asia'),
('Australia','Australia','Australia and New Zealand'),
('Australia','Fiji','Melanesia'),
('Australia','Kiribati','Micronesia'),
('Australia','Marshall Islands','Micronesia'),
('Australia','Micronesia','Micronesia'),
('Australia','Nauru','Micronesia'),
('Australia','New Zealand','Australia and New Zealand'),
('Australia','Palau','Micronesia'),
('Australia','Papua New Guinea','Melanesia'),
('Australia','Samoa','Polynesia'),
('Australia','Solomon Islands','Melanesia'),
('Australia','Tonga','Polynesia'),
('Australia','Tuvalu','Micronesia'),
('Australia','Vanuatu','Melanesia'),
('Europe','Albania','Southern Europe'),
('Europe','Andorra','Southern Europe'),
('Europe','Austria','Western Europe'),
('Europe','Belarus','Eastern Europe'),
('Europe','Belgium','Western Europe'),
('Europe','Bosnia and Herzegovina','Southern Europe'),
('Europe','Bulgaria','Eastern Europe'),
('Europe','Croatia','Southern Europe'),
('Europe','Czech Republic','Eastern Europe'),
('Europe','Denmark','Northern Europe'),
('Europe','Estonia','Northern Europe'),
('Europe','Finland','Northern Europe'),
('Europe','France','Western Europe'),
('Europe','Germany','Western Europe'),
('Europe','Greece','Southern Europe'),
('Europe','Hungary','Eastern Europe'),
('Europe','Iceland','Northern Europe'),
('Europe','Ireland','Northern Europe'),
('Europe','Italy','Southern Europe'),
('Europe','Kosovo','Southern Europe'),
('Europe','Latvia','Northern Europe'),
('Europe','Liechtenstein','Western Europe'),
('Europe','Lithuania','Northern Europe'),
('Europe','Luxembourg','Western Europe'),
('Europe','Malta','Southern Europe'),
('Europe','Moldova','Eastern Europe'),
('Europe','Monaco','Western Europe'),
('Europe','Montenegro','Southern Europe'),
('Europe','Netherlands','Western Europe'),
('Europe','North Macedonia','Southern Europe'),
('Europe','Norway','Northern Europe'),
('Europe','Poland','Eastern Europe'),
('Europe','Portugal','Southern Europe'),
('Europe','Romania','Eastern Europe'),
('Europe','Russia','Eastern Europe'),
('Europe','San Marino','Southern Europe'),
('Europe','Serbia','Southern Europe'),
('Europe','Slovakia','Eastern Europe'),
('Europe','Slovenia','Southern Europe'),
('Europe','Spain','Southern Europe'),
('Europe','Sweden','Northern Europe'),
('Europe','Switzerland','Western Europe'),
('Europe','Ukraine','Eastern Europe'),
('Europe','United Kingdom','Northern Europe'),
('Europe','Vatican City','Southern Europe'),
('North America','Antigua and Barbuda','Caribbean'),
('North America','Bahamas','Caribbean'),
('North America','Barbados','Caribbean'),
('North America','Belize','Central America'),
('North America','Canada','Northern America'),
('North America','Costa Rica','Central America'),
('North America','Cuba','Caribbean'),
('North America','Dominica','Caribbean'),
('North America','Dominican Republic','Caribbean'),
('North America','El Salvador','Central America'),
('North America','Grenada','Caribbean'),
('North America','Guatemala','Central America'),
('North America','Haiti','Caribbean'),
('North America','Honduras','Central America'),
('North America','Jamaica','Caribbean'),
('North America','Mexico','Northern America'),
('North America','Nicaragua','Central America'),
('North America','Panama','Central America'),
('North America','Saint Kitts and Nevis','Caribbean'),
('North America','Saint Lucia','Caribbean'),
('North America','Saint Vincent and the Grenadines','Caribbean'),
('North America','Trinidad and Tobago','Caribbean'),
('North America','United States of America','Northern America'),
('South America','Argentina','Southern America'),
('South America','Bolivia','Southern America'),
('South America','Brazil','Southern America'),
('South America','Chile','Southern America'),
('South America','Colombia','Southern America'),
('South America','Ecuador','Southern America'),
('South America','Guyana','Southern America'),
('South America','Paraguay','Southern America'),
('South America','Peru','Southern America'),
('South America','Suriname','Southern America'),
('South America','Uruguay','Southern America'),
('South America','Venezuela','Southern America')